#%RAML 1.0
title: signUp
baseUri: http://api.piarch-a-signup.com/
version : 1
documentation:
  - title: Welcome
    content: |
      Welcome to the Sign-up Documentation.
/signup:
  description: System signup
  get:
    queryParameters:
        access_token:
          description: "The access token provided by the authentication application"
          example: "eyJhbGciOiJIUzI1NiI.eyJzdWIiOiIxMjM0NTY.TJVA95OrM7E2cBab30RM"
          required: true
          type: string
    responses:
      200:
       body:
        application/json:
         type: |
          {
          "type": "object",
          "properties": {
            "answer":"boolean"
          }
          }
        example: |
          {
          "answer":true
          }
      400:
        description: |
          Bad Request
