#%RAML 1.0
title: signUp
baseUri: http://api.piarch-a-signup.com/
version : 1
documentation:
  - title: Welcome
    content: |
      Welcome to the Sign-up Documentation.
/signup:
  description: System signup
  get:
    responses:
      200:
       body:
        application/json:
         type: |
          {
          "type": "object",
          "properties": {
            "username": {
              "type": "string"
            },
            "password": {
              "type": "string"
              },
            "token": {
              "type": "string"
              }
          }
          }
        example: |
          {
          "username": "korburak",
          "password": "123456",
          "token": "eyJhbGciOi.eyJzdWIiOiJrb3Jid.La0DZMbwEl6RDL3Q"
          }
      400:
        description: |
          Bad Request
